### ISSUE TITLE
I want to handle more file,how to prepare the inputs and targets?

### ISSUE THREAD

**Issue by guduxingzou** [igormq/ctc_tensorflow_example#1]
I want to handle more file,how to prepare the inputs and targets?

thanks!

**Comment by igormq** [comment]
Hi @guduxingzou, thank you for your question. If the files aren't bigger than the CPU/GPU memory you can put all them in a memory and separate them in batches. Otherwise, you will need to load them from the disk dynamically, like the [tutorial](https://www.tensorflow.org/versions/r0.10/how_tos/reading_data/index.html#reading-from-files) in tensorflow's website.

Best regards.
